import Head from 'next/head'
import Subscribers from '../components/Subscribers'
import Views from '@/components/Views'
import Videos from '@/components/Videos'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='flex min-h-screen w-screen justify-center items-center overflow-x-hidden overflow-y-auto'>
        <div className="flex flex-col items-center border-3 border-blue-500 w-full">
          <h1 className=" text-4xl font-leckton font-semibold mt-20">Crypto YouTube Barometer</h1>
          <Subscribers/>
          <Views/>
          <Videos/>
        </div>
      </div>
    </>
  )
}
