import Head from 'next/head'
import axios from 'axios'
import { useEffect } from 'react'

export default function Home() {

  useEffect(() => {
    const fetchData = async () => {
      const result = await axios.get('/api/get-stats')
      console.log(result.data)
    }
    fetchData()
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <p>Working!</p>
      </div>
    </>
  )
}
